name: CD Pipeline

on: 
  push: 
    branches:
      - main

jobs:
  build-and-push: 
    name: Build and Push docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Log in Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-ci-cd-api:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/spring-ci-cd-api:latest ${{ secrets.DOCKER_USERNAME }}/spring-ci-cd-api:${{ github.run_number }}

      - name: Push Docker image to Docker Hub
        run : |
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-ci-cd-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-ci-cd-api:${{ github.run_number }}
